## Part 1: Explore the Data

Import the data and use Pandas to learn more about the dataset.

In [1]:
import pandas as pd

df = pd.read_csv('client_dataset.csv')
df.head()

,first,last,job,phone,email,client_id,order_id,order_date,order_week,order_year,item_id,category,subcategory,unit_price,unit_cost,unit_weight,qty,line_number
0,Donald,Harding,Immunologist,793-904-7725x39308,harding.donald.7185@sullivan.com,58515,8953482,2023-04-28,17,2023,EUD29711-63-6U,decor,wall art,1096.80,762.71,7.50,105,1
1,Tiffany,Myers,Music therapist,201.442.4543x942,myers.t.6537@ferguson-johnson.net,37609,8069089,2023-05-19,20,2023,XDA18116-89-4A,consumables,pens,24.95,15.09,1.49,21,0
2,Shannon,Watson,Immunologist,687.737.9424x8503,swatson8146@payne.net,57113,1902144,2023-01-29,4,2023,ABE59463-05-7E,software,project management,13.52,7.86,1.68,39,6
3,Nathan,Baker,Accounting technician,827-788-8123x012,bakernathan@benson.com,46554,9031802,2023-04-25,17,2023,ZMM00836-65-0C,consumables,pens,36.42,24.85,1.23,29,3
4,Christina,Schwartz,Chiropractor,265-829-3643,christinaschwartz9252@mcconnell.com,92089,1322274,2023-05-28,21,2023,BZX55559-12-3X,consumables,misc,195.10,108.17,46.43,20,1

In [2]:
# View the column names in the data
column_names = df.columns.tolist()
print(column_names)

['first', 'last', 'job', 'phone', 'email', 'client_id', 'order_id', 'order_date', 'order_week', 'order_year', 'item_id', 'category', 'subcategory', 'unit_price', 'unit_cost', 'unit_weight', 'qty', 'line_number']

In [3]:
# Use the describe function to gather some basic statistics
statistics = df.describe()
print(statistics)

          client_id      order_id    order_week    order_year    unit_price  \
count  54639.000000  5.463900e+04  54639.000000  54639.000000  54639.000000
mean   54837.869416  5.470190e+06     11.359139   2022.993064    136.267207
std    25487.438231  2.599807e+06      7.023499      0.082997    183.873135
min    10033.000000  1.000886e+06      1.000000   2022.000000      0.010000
25%    33593.000000  3.196372e+06      6.000000   2023.000000     20.800000
50%    53305.000000  5.496966e+06     11.000000   2023.000000     68.310000
75%    78498.000000  7.733869e+06     17.000000   2023.000000    173.160000
max    99984.000000  9.998480e+06     52.000000   2023.000000   1396.230000

          unit_cost   unit_weight           qty   line_number
count  54639.000000  54639.000000  5.463900e+04  54639.000000
mean      99.446073      5.004116  5.702646e+02      2.979667
std      133.164267      5.326599  1.879552e+04      2.436320
min        0.010000      0.000000  0.000000e+00      0.000000
25%       14.840000      1.450000  3.200000e+01      1.000000
50%       49.890000      3.240000  6.800000e+01      3.000000
75%      125.570000      6.890000  1.700000e+02      5.000000
max      846.270000     46.430000  3.958244e+06      9.000000

In [4]:
# Use this space to do any additional research
# and familiarize yourself with the data.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54639 entries, 0 to 54638
Data columns (total 18 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   first        54639 non-null  object
 1   last         54639 non-null  object
 2   job          54639 non-null  object
 3   phone        54639 non-null  object
 4   email        54639 non-null  object
 5   client_id    54639 non-null  int64
 6   order_id     54639 non-null  int64
 7   order_date   54639 non-null  object
 8   order_week   54639 non-null  int64
 9   order_year   54639 non-null  int64
 10  item_id      54639 non-null  object
 11  category     54639 non-null  object
 12  subcategory  54639 non-null  object
 13  unit_price   54639 non-null  float64
 14  unit_cost    54639 non-null  float64
 15  unit_weight  54639 non-null  float64
 16  qty          54639 non-null  int64
 17  line_number  54639 non-null  int64
dtypes: float64(3), int64(6), object(9)
memory usage: 7.5+ MB

In [5]:
# What three item categories had the most entries?
top_categories = df["category"].value_counts().head(3)
print(top_categories)

category
consumables    23538
furniture      11915
software        8400
Name: count, dtype: int64

In [6]:
# For the category with the most entries, which subcategory had the most entries?
top_category = df["category"].value_counts().idxmax()
top_category_df = df[df["category"] == top_category]
top_subcategory = top_category_df["subcategory"].value_counts().idxmax()
print(f"{top_category}: {top_subcategory} ")

consumables: bathroom supplies

In [7]:
# Which five clients had the most entries in the data?
top_clients = df["category"].value_counts().head()

In [8]:
# Store the client ids of those top 5 clients in a list.
client_ids = top_clients.value_counts().head()
print(client_ids)

count
23538    1
11915    1
8400     1
7954     1
2832     1
Name: count, dtype: int64

In [9]:
# How many total units (the qty column) did the client with the most entries order order?
client_counts = df['client_id'].value_counts()
top_client = top_clients.idxmax()
top_client_data = df[df['client_id'] == top_client]
total_units = top_client_data["qty"].sum()
print(f"{top_client}: {total_units}")

consumables: 0

## Part 2: Transform the Data
Do we know that this client spent the more money than client 66037? If not, how would we find out? Transform the data using the steps below to prepare it for analysis.

In [10]:
# Create a column that calculates the subtotal for each line using the unit_price and the qty
df['subtotal'] = df['unit_price'] * df['qty']
print(df)

           first       last                      job               phone  \
0         Donald    Harding             Immunologist  793-904-7725x39308
1        Tiffany      Myers          Music therapist    201.442.4543x942
2        Shannon     Watson             Immunologist   687.737.9424x8503
3         Nathan      Baker    Accounting technician    827-788-8123x012
4      Christina   Schwartz             Chiropractor        265-829-3643
...          ...        ...                      ...                 ...
54634     Lauren      Reese           Radio producer  977.877.5272x11382
54635    Derrick      Moore                 Musician        358.661.5483
54636     Monica  Gutierrez         Graphic designer    294.805.9100x339
54637      Wanda    Solomon             Toxicologist       (311)767-4924
54638     Dwayne       Bell  Chief Financial Officer   606-619-7667x9508

                                     email  client_id  order_id  order_date  \
0         harding.donald.7185@sullivan.com      58515   8953482  2023-04-28
1        myers.t.6537@ferguson-johnson.net      37609   8069089  2023-05-19
2                    swatson8146@payne.net      57113   1902144  2023-01-29
3                   bakernathan@benson.com      46554   9031802  2023-04-25
4      christinaschwartz9252@mcconnell.com      92089   1322274  2023-05-28
...                                    ...        ...       ...         ...
54634   late_reese_4081@montoya-chavez.org      29043   9021716  2023-04-26
54635         derrick.moore.2602@pope.info      41908   6290153  2023-02-08
54636            gutierrezm3195@morris.org      35176   8692622  2023-03-05
54637            solomonwanda5962@ross.org      24485   7592730  2023-01-18
54638                     belld@galvan.com      24007   7489403  2023-01-04

       order_week  order_year         item_id     category  \
0              17        2023  EUD29711-63-6U        decor
1              20        2023  XDA18116-89-4A  consumables
2               4        2023  ABE59463-05-7E     software
3              17        2023  ZMM00836-65-0C  consumables
4              21        2023  BZX55559-12-3X  consumables
...           ...         ...             ...          ...
54634          17        2023  UCA28532-31-0B     software
54635           6        2023  EBD29277-23-7U  consumables
54636           9        2023  EBD30093-55-9Z  consumables
54637           3        2023  XMZ38239-49-3D    furniture
54638           1        2023  ZCZ05589-50-5D     software

              subcategory  unit_price  unit_cost  unit_weight   qty  \
0                wall art     1096.80     762.71         7.50   105
1                    pens       24.95      15.09         1.49    21
2      project management       13.52       7.86         1.68    39
3                    pens       36.42      24.85         1.23    29
4                    misc      195.10     108.17        46.43    20
...                   ...         ...        ...          ...   ...
54634           logistics       83.13      51.60         2.25    33
54635    kitchen supplies      206.59     175.46        11.70    47
54636   bathroom supplies       65.66      57.31         4.16   475
54637              stands        1.48       1.22        18.04   112
54638  project management        3.01       1.61         2.07  1031

       line_number   subtotal
0                1  115164.00
1                0     523.95
2                6     527.28
3                3    1056.18
4                1    3902.00
...            ...        ...
54634            8    2743.29
54635            0    9709.73
54636            6   31188.50
54637            0     165.76
54638            5    3103.31

[54639 rows x 19 columns]

In [11]:
# Create a column for shipping price.
# Assume a shipping price of $7 per pound for orders over 50 pounds and $10 per pound for items 50 pounds or under.

def calculate_shipping(weight):
    if weight > 50:
        return 7 * weight
    else:
        return 10 * weight
    df['shipping_price'] = df['weight'].apply(calculate_shipping)
    print(df)

In [12]:
# Create a column for the total price using the subtotal and the shipping price along with a sales tax of 9.25%
sales_tax_rate = 0.0925
df['total_price'] = df['subtotal'] * sales_tax_rate
print(df)

           first       last                      job               phone  \
0         Donald    Harding             Immunologist  793-904-7725x39308
1        Tiffany      Myers          Music therapist    201.442.4543x942
2        Shannon     Watson             Immunologist   687.737.9424x8503
3         Nathan      Baker    Accounting technician    827-788-8123x012
4      Christina   Schwartz             Chiropractor        265-829-3643
...          ...        ...                      ...                 ...
54634     Lauren      Reese           Radio producer  977.877.5272x11382
54635    Derrick      Moore                 Musician        358.661.5483
54636     Monica  Gutierrez         Graphic designer    294.805.9100x339
54637      Wanda    Solomon             Toxicologist       (311)767-4924
54638     Dwayne       Bell  Chief Financial Officer   606-619-7667x9508

                                     email  client_id  order_id  order_date  \
0         harding.donald.7185@sullivan.com      58515   8953482  2023-04-28
1        myers.t.6537@ferguson-johnson.net      37609   8069089  2023-05-19
2                    swatson8146@payne.net      57113   1902144  2023-01-29
3                   bakernathan@benson.com      46554   9031802  2023-04-25
4      christinaschwartz9252@mcconnell.com      92089   1322274  2023-05-28
...                                    ...        ...       ...         ...
54634   late_reese_4081@montoya-chavez.org      29043   9021716  2023-04-26
54635         derrick.moore.2602@pope.info      41908   6290153  2023-02-08
54636            gutierrezm3195@morris.org      35176   8692622  2023-03-05
54637            solomonwanda5962@ross.org      24485   7592730  2023-01-18
54638                     belld@galvan.com      24007   7489403  2023-01-04

       order_week  order_year         item_id     category  \
0              17        2023  EUD29711-63-6U        decor
1              20        2023  XDA18116-89-4A  consumables
2               4        2023  ABE59463-05-7E     software
3              17        2023  ZMM00836-65-0C  consumables
4              21        2023  BZX55559-12-3X  consumables
...           ...         ...             ...          ...
54634          17        2023  UCA28532-31-0B     software
54635           6        2023  EBD29277-23-7U  consumables
54636           9        2023  EBD30093-55-9Z  consumables
54637           3        2023  XMZ38239-49-3D    furniture
54638           1        2023  ZCZ05589-50-5D     software

              subcategory  unit_price  unit_cost  unit_weight   qty  \
0                wall art     1096.80     762.71         7.50   105
1                    pens       24.95      15.09         1.49    21
2      project management       13.52       7.86         1.68    39
3                    pens       36.42      24.85         1.23    29
4                    misc      195.10     108.17        46.43    20
...                   ...         ...        ...          ...   ...
54634           logistics       83.13      51.60         2.25    33
54635    kitchen supplies      206.59     175.46        11.70    47
54636   bathroom supplies       65.66      57.31         4.16   475
54637              stands        1.48       1.22        18.04   112
54638  project management        3.01       1.61         2.07  1031

       line_number   subtotal   total_price
0                1  115164.00  10652.670000
1                0     523.95     48.465375
2                6     527.28     48.773400
3                3    1056.18     97.696650
4                1    3902.00    360.935000
...            ...        ...           ...
54634            8    2743.29    253.754325
54635            0    9709.73    898.150025
54636            6   31188.50   2884.936250
54637            0     165.76     15.332800
54638            5    3103.31    287.056175

[54639 rows x 20 columns]

In [13]:
# Create a column for the cost of each line using unit cost, qty, and
# shipping price (assume the shipping cost is exactly what is charged to the client).
def calculate_shipping(weight):
    if weight > 50:
        return 7 * weight
    else:
        return 10 * weight
    df['shipping_price'] = df['weight'].apply(calculate_shipping)
    df['line_cost'] = df['unit_cost'] * df['qty']
    print(df)

In [16]:
# Create a column for the profit of each line using line cost and line price
df['line_price'] = df['line_number'] * df['qty']
df['line_cost'] = df['unit_price'] *df['qty']
df['profit'] = df['line_cost'] - df['line_price']
df

,first,last,job,phone,email,client_id,order_id,order_date,order_week,order_year,...,unit_price,unit_cost,unit_weight,qty,line_number,subtotal,total_price,line_price,line_cost,profit
0,Donald,Harding,Immunologist,793-904-7725x39308,harding.donald.7185@sullivan.com,58515,8953482,2023-04-28,17,2023,...,1096.80,762.71,7.50,105,1,115164.00,10652.670000,105,115164.00,115059.00
1,Tiffany,Myers,Music therapist,201.442.4543x942,myers.t.6537@ferguson-johnson.net,37609,8069089,2023-05-19,20,2023,...,24.95,15.09,1.49,21,0,523.95,48.465375,0,523.95,523.95
2,Shannon,Watson,Immunologist,687.737.9424x8503,swatson8146@payne.net,57113,1902144,2023-01-29,4,2023,...,13.52,7.86,1.68,39,6,527.28,48.773400,234,527.28,293.28
3,Nathan,Baker,Accounting technician,827-788-8123x012,bakernathan@benson.com,46554,9031802,2023-04-25,17,2023,...,36.42,24.85,1.23,29,3,1056.18,97.696650,87,1056.18,969.18
4,Christina,Schwartz,Chiropractor,265-829-3643,christinaschwartz9252@mcconnell.com,92089,1322274,2023-05-28,21,2023,...,195.10,108.17,46.43,20,1,3902.00,360.935000,20,3902.00,3882.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54634,Lauren,Reese,Radio producer,977.877.5272x11382,late_reese_4081@montoya-chavez.org,29043,9021716,2023-04-26,17,2023,...,83.13,51.60,2.25,33,8,2743.29,253.754325,264,2743.29,2479.29
54635,Derrick,Moore,Musician,358.661.5483,derrick.moore.2602@pope.info,41908,6290153,2023-02-08,6,2023,...,206.59,175.46,11.70,47,0,9709.73,898.150025,0,9709.73,9709.73
54636,Monica,Gutierrez,Graphic designer,294.805.9100x339,gutierrezm3195@morris.org,35176,8692622,2023-03-05,9,2023,...,65.66,57.31,4.16,475,6,31188.50,2884.936250,2850,31188.50,28338.50
54637,Wanda,Solomon,Toxicologist,(311)767-4924,solomonwanda5962@ross.org,24485,7592730,2023-01-18,3,2023,...,1.48,1.22,18.04,112,0,165.76,15.332800,0,165.76,165.76
54638,Dwayne,Bell,Chief Financial Officer,606-619-7667x9508,belld@galvan.com,24007,7489403,2023-01-04,1,2023,...,3.01,1.61,2.07,1031,5,3103.31,287.056175,5155,3103.31,-2051.69

## Part 3: Confirm your work
You have email receipts showing that the total prices for 3 orders. Confirm that your calculations match the receipts. Remember, each order has multiple lines.

Order ID 2742071 had a total price of \$152,811.89

Order ID 2173913 had a total price of \$162,388.71

Order ID 6128929 had a total price of \$923,441.25

In [17]:
# Check your work using the totals above
order_id =  df["category"].value_counts().idxmax()
print(df)

           first       last                      job               phone  \
0         Donald    Harding             Immunologist  793-904-7725x39308
1        Tiffany      Myers          Music therapist    201.442.4543x942
2        Shannon     Watson             Immunologist   687.737.9424x8503
3         Nathan      Baker    Accounting technician    827-788-8123x012
4      Christina   Schwartz             Chiropractor        265-829-3643
...          ...        ...                      ...                 ...
54634     Lauren      Reese           Radio producer  977.877.5272x11382
54635    Derrick      Moore                 Musician        358.661.5483
54636     Monica  Gutierrez         Graphic designer    294.805.9100x339
54637      Wanda    Solomon             Toxicologist       (311)767-4924
54638     Dwayne       Bell  Chief Financial Officer   606-619-7667x9508

                                     email  client_id  order_id  order_date  \
0         harding.donald.7185@sullivan.com      58515   8953482  2023-04-28
1        myers.t.6537@ferguson-johnson.net      37609   8069089  2023-05-19
2                    swatson8146@payne.net      57113   1902144  2023-01-29
3                   bakernathan@benson.com      46554   9031802  2023-04-25
4      christinaschwartz9252@mcconnell.com      92089   1322274  2023-05-28
...                                    ...        ...       ...         ...
54634   late_reese_4081@montoya-chavez.org      29043   9021716  2023-04-26
54635         derrick.moore.2602@pope.info      41908   6290153  2023-02-08
54636            gutierrezm3195@morris.org      35176   8692622  2023-03-05
54637            solomonwanda5962@ross.org      24485   7592730  2023-01-18
54638                     belld@galvan.com      24007   7489403  2023-01-04

       order_week  order_year  ... unit_price unit_cost unit_weight   qty  \
0              17        2023  ...    1096.80    762.71        7.50   105
1              20        2023  ...      24.95     15.09        1.49    21
2               4        2023  ...      13.52      7.86        1.68    39
3              17        2023  ...      36.42     24.85        1.23    29
4              21        2023  ...     195.10    108.17       46.43    20
...           ...         ...  ...        ...       ...         ...   ...
54634          17        2023  ...      83.13     51.60        2.25    33
54635           6        2023  ...     206.59    175.46       11.70    47
54636           9        2023  ...      65.66     57.31        4.16   475
54637           3        2023  ...       1.48      1.22       18.04   112
54638           1        2023  ...       3.01      1.61        2.07  1031

       line_number   subtotal   total_price  line_price  line_cost     profit
0                1  115164.00  10652.670000         105  115164.00  115059.00
1                0     523.95     48.465375           0     523.95     523.95
2                6     527.28     48.773400         234     527.28     293.28
3                3    1056.18     97.696650          87    1056.18     969.18
4                1    3902.00    360.935000          20    3902.00    3882.00
...            ...        ...           ...         ...        ...        ...
54634            8    2743.29    253.754325         264    2743.29    2479.29
54635            0    9709.73    898.150025           0    9709.73    9709.73
54636            6   31188.50   2884.936250        2850   31188.50   28338.50
54637            0     165.76     15.332800           0     165.76     165.76
54638            5    3103.31    287.056175        5155    3103.31   -2051.69

[54639 rows x 23 columns]

## Part 4: Summarize and Analyze
Use the new columns with confirmed values to find the following information.

In [18]:
# How much did each of the top 5 clients by quantity spend? Check your work from Part 1 for client ids.

df['total_spend'] = df['line_price'] * df['qty']
grouped_df = df.groupby('client_id').agg({'qty': 'sum', 'total_spend': 'sum'})
top_clients = grouped_df.sort_values(by='qty', ascending=False).head()
print(top_clients)

               qty     total_spend
client_id
78965      4033302  15668094983503
86721      1010426   2864817520927
30143       846069   1419887514751
85931       644423   1218530251511
77354       506382    244793966860

In [21]:
# Create a summary DataFrame showing the totals for the for the top 5 clients with the following information:
# total units purchased, total shipping price, total revenue, and total profit.
df['shipping_price'] = df['unit_weight'].apply(calculate_shipping)
df['revenue'] = df['unit_price'] * df['qty'] + df['shipping_price'] + df['profit']
df['units_purchased'] = df['unit_cost'] * df['qty']
summary = df.groupby('client_id').agg({'units_purchased': 'sum', 'shipping_price': 'sum', 'revenue': 'sum', 'profit': 'sum'}).reset_index()
top_5_clients = summary.sort_values(by='revenue', ascending=False).head()
print(top_5_clients)

     client_id  units_purchased  shipping_price       revenue        profit
758      78965     4.032301e+08          7383.3  1.185982e+09  5.909279e+08
840      85931     1.180003e+08          2763.0  4.124558e+08  2.052602e+08
320      38473     1.358098e+08          7832.2  3.253038e+08  1.616754e+08
850      86721     7.395587e+07          6154.6  2.001238e+08  9.853455e+07
821      84344     7.418983e+07          6944.0  1.839411e+08  9.106236e+07

In [ ]:
# Format the data and rename the columns to names suitable for presentation.
top_5_clients = ['Client ID', 'Total Units Purchased', 'Total Shipping Price', 'Total Revenue', 'Total Profit']
print(top_5_clients)
# Define the money columns. 
df['revenue'] = df['revenue'].apply(lambda x: f"${x:,.2f}")
df['profit'] = df['profit'].apply(lambda x: f"${x:,.2f}")
df 

# Define a function that converts a dollar amount to millions.
def to_millions(amount):
    return amount / 1_000_000

# Apply the currency_format_millions function to only the money columns. 
df['revenue (in millions)'] = df['revenue'].apply(to_millions)
df['profit (in millions)'] = df['profit'].apply(to_millions)
df

# Rename the columns to reflect the change in the money format. 
df['revenue'] = ('Total Revenue (Millions)')
df['profit'] = ('Total Profit (Millions)')
print(df)

In [ ]:
# Sort the updated data by "Total Profit (millions)" form highest to lowest and assign the sort to a new DatFrame.
sorted_df = df.sort_values(by='Total Profit (millions)', ascending=False)
print(sorted_df)